In [72]:
import pandas as pd
from scipy.stats import spearmanr

In [6]:
phyl_poincare = pd.read_csv("phyl_poincare.csv")

In [8]:
phyl_poincare

          pm1       pm2
0   -0.170347  0.890286
1   -0.579990 -0.745503
2    0.833874 -0.407057
3   -0.152546  0.911079
4   -0.018704 -0.909797
..        ...       ...
247 -0.494778 -0.585128
248 -0.828712  0.352412
249 -0.571357 -0.746109
250 -0.879661  0.028909
251 -0.699363  0.113743

[252 rows x 2 columns]

In [55]:
phyl = pd.read_csv("out_phyl.csv")

In [56]:
phyl

,1,2,3,4,5,6,7,8,9,10,...,243,244,245,246,247,248,249,250,251,252
0,0.000000,0.020364,0.022568,0.024713,0.023570,0.023615,0.024607,0.021254,0.022047,0.022868,...,0.022062,0.032975,0.034126,0.034768,0.028960,0.026797,0.026272,0.024387,0.028972,0.031496
1,0.020364,0.000000,0.010615,0.012760,0.011618,0.011662,0.013878,0.007727,0.011692,0.012513,...,0.023655,0.028806,0.029957,0.030598,0.024791,0.022628,0.022102,0.020217,0.024803,0.027327
2,0.022568,0.010615,0.000000,0.011632,0.010489,0.010534,0.016081,0.011505,0.013896,0.014717,...,0.025858,0.031009,0.032161,0.032802,0.026995,0.024831,0.024306,0.022421,0.027007,0.029530
3,0.024713,0.012760,0.011632,0.000000,0.001429,0.002798,0.018226,0.013650,0.016041,0.016862,...,0.028003,0.033155,0.034306,0.034947,0.029140,0.026977,0.026451,0.024566,0.029152,0.031675
4,0.023570,0.011618,0.010489,0.001429,0.000000,0.001656,0.017084,0.012507,0.014898,0.015719,...,0.026861,0.032012,0.033163,0.033804,0.027997,0.025834,0.025309,0.023423,0.028009,0.030533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,0.026797,0.022628,0.024831,0.026977,0.025834,0.025878,0.026870,0.023517,0.024310,0.025131,...,0.030087,0.031806,0.032958,0.033599,0.027792,0.000000,0.008504,0.004719,0.007447,0.030327
248,0.026272,0.022102,0.024306,0.026451,0.025309,0.025353,0.026345,0.022992,0.023785,0.024606,...,0.029562,0.031281,0.032433,0.033074,0.027267,0.008504,0.000000,0.006093,0.010679,0.029802
249,0.024387,0.020217,0.022421,0.024566,0.023423,0.023468,0.024460,0.021107,0.021900,0.022721,...,0.027677,0.029396,0.030547,0.031189,0.025381,0.004719,0.006093,0.000000,0.006895,0.027917
250,0.028972,0.024803,0.027007,0.029152,0.028009,0.028053,0.029046,0.025692,0.026485,0.027306,...,0.032263,0.033982,0.035133,0.035774,0.029967,0.007447,0.010679,0.006895,0.000000,0.032503
251,0.031496,0.027327,0.029530,0.031675,0.030533,0.030577,0.031569,0.028216,0.029009,0.029830,...,0.034786,0.036229,0.037380,0.038021,0.011359,0.030327,0.029802,0.027917,0.032503,0.000000

In [48]:
phyl.iloc[0][1]

0.0203643198099957

# Calculate the distance in PoincarÃ©

In [66]:
def dist_euclidian(xa, ya, xb, yb):
    return ((xb - xa)**2 + (yb - ya)**2)**0.5

In [73]:
dist_poincare = pd.DataFrame(0.0, index=range(252), columns=range(252))

for i in range(len(dist_poincare[0])):
    for j in range(i+1, len(dist_poincare[0])):
        dist_poincare.iloc[i][j] = dist_euclidian(phyl_poincare.iloc[i][0], phyl_poincare.iloc[i][1], phyl_poincare.iloc[j][0], phyl_poincare.iloc[j][1])
        dist_poincare.iloc[j][i] = dist_euclidian(phyl_poincare.iloc[i][0], phyl_poincare.iloc[i][1], phyl_poincare.iloc[j][0], phyl_poincare.iloc[j][1])
print(dist_poincare)

          0         1         2         3         4         5         6    \
0    0.000000  1.686302  1.640598  0.027371  1.806460  0.074312  1.637171
1    1.686302  0.000000  1.453808  1.710840  0.584838  1.736013  1.459832
2    1.640598  1.453808  0.000000  1.646362  0.989766  1.628378  0.008847
3    0.027371  1.710840  1.646362  0.000000  1.825788  0.050114  1.642803
4    1.806460  0.584838  0.989766  1.825788  0.000000  1.835803  0.997426
..        ...       ...       ...       ...       ...       ...       ...
247  1.510663  0.181608  1.340532  1.534848  0.576244  1.558886  1.345870
248  0.850149  1.125735  1.827836  0.877102  1.499762  0.922903  1.828594
249  1.684814  0.008655  1.445555  1.709290  0.576385  1.734249  1.451591
250  1.115840  0.830371  1.768126  1.143206  1.273741  1.184342  1.770444
251  0.939616  0.867498  1.619274  0.966826  1.229199  1.005408  1.620919

          7         8         9    ...       242       243       244  \
0    0.904515  1.352928  0.942499  ...  0.852606  0.862270  0.205331
1    0.909687  0.334725  0.886479  ...  1.397511  1.395702  1.736266
2    1.633165  1.358934  1.649239  ...  0.792238  0.782505  1.513611
3    0.931793  1.377709  0.969790  ...  0.856713  0.866410  0.190024
4    1.264727  0.707727  1.256558  ...  1.235615  1.229973  1.788928
..        ...       ...       ...  ...       ...       ...       ...
247  0.769107  0.172482  0.750481  ...  1.224334  1.222932  1.556279
248  0.235061  0.825611  0.246050  ...  1.229625  1.235820  1.010923
249  0.911457  0.334015  0.888537  ...  1.391924  1.390070  1.733795
250  0.221073  0.568419  0.183450  ...  1.296272  1.300379  1.247984
251  0.042621  0.557045  0.030516  ...  1.105227  1.109750  1.059885

          245       246       247       248       249       250       251
0    1.476276  1.508328  1.510663  0.850149  1.684814  1.115840  0.939616
1    0.476730  0.186133  0.181608  1.125735  0.008655  0.830371  0.867498
2    0.981157  1.332295  1.340532  1.827836  1.445555  1.768126  1.619274
3    1.496698  1.532445  1.534848  0.877102  1.709290  1.143206  0.966826
4    0.343200  0.569807  0.576244  1.499762  0.576385  1.273741  1.229199
..        ...       ...       ...       ...       ...       ...       ...
247  0.363852  0.008252  0.000000  0.995235  0.178267  0.724690  0.728200
248  1.168980  0.997460  0.995235  0.000000  1.128264  0.327491  0.271467
249  0.468813  0.182488  0.178267  1.128264  0.000000  0.834088  0.869327
250  0.968533  0.728587  0.724690  0.327491  0.834088  0.000000  0.199259
251  0.901115  0.729978  0.728200  0.271467  0.869327  0.199259  0.000000

[252 rows x 252 columns]

# Comparing with distance matrix

In [80]:
# Calculate spearman correlation
correlation, p_value = spearmanr(dist_poincare, phyl)
correlation = pd.DataFrame(correlation)

In [79]:
correlation